name: "CVE Scan"
on:
  workflow_dispatch: { }
  schedule:
    - cron: '0 9 * * *'
  push:
    branches:
      - 'add-image-cve-scan'
jobs:
  scan-images:
    name: Scan latest public image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ docker-asciidoctor ]
        tag: [ latest ]
    steps:
      - name: Pull
        run: docker pull asciidoctor/${{ matrix.image }}:${{ matrix.tag }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.2.1
        with:
          image-ref: 'docker.io/asciidoctor/${{ matrix.image }}:${{ matrix.tag }}'
          severity: 'CRITICAL,HIGH'
          format: 'table'
          exit-code: '1'
